<?php

namespace ContainerTbFvHWd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S93nYnOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S93nYnO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S93nYnO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'book' => ['privates', '.errored..service_locator.S93nYnO.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.S93nYnO": it references class "App\\Entity\\Book" but no such service exists.'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'book' => 'App\\Entity\\Book',
            'slugger' => '?',
        ]);
    }
}
