<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTbFvHWd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTbFvHWd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTbFvHWd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTbFvHWd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTbFvHWd\App_KernelDevDebugContainer([
    'container.build_hash' => 'TbFvHWd',
    'container.build_id' => '1f371ffc',
    'container.build_time' => 1630284345,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTbFvHWd');
